In [2]:
import numpy as np
np.__version__

'1.18.4'

In [5]:
#This is how we create an array with numpy
a = np.array([1,23,4,56,])


In [6]:
B = np.array([4,56,3.3,45])

In [8]:
a.dtype

dtype('int32')

In [9]:
B.dtype

dtype('float64')

In [11]:
#Immutability and downcasting
a[0] = 8.5

In [12]:
a

array([ 8, 23,  4, 56])

In [13]:
#Numpy Dimensions

In [14]:
# 1D
c = np.array([[1,23,4,56],[2,6,87]])

In [15]:
print(c.ndim)

1


In [31]:
# if you have a list of two 1D then the list becomes a 2D
d = np.array([[[1,3,4],[2,5,7],[5,5,2]],[[34,-4,6],[2,5,7],[5,7,21]]])

In [22]:
print(d.ndim)

2


In [32]:
d.shape

(2, 3, 3)

In [35]:
d.shape[0]

2

In [36]:
d[0,1,2]

7

In [41]:
a = np.arange(10)

In [42]:
#Numpy Array Slicing

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
a[-2] #To pick the second last element

8

In [44]:
a[2:6]

array([2, 3, 4, 5])

In [46]:
a[::-1] #To reverse the array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [3]:
f = np.array([3,4,6,7,9,2,5,6])

In [4]:
f[[1,2]]

array([4, 6])

In [5]:
K = np.random.rand(1000000)
%timeit np.sum(K)

1.46 ms ± 271 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
sum